listener 8000
protocol mqtt
# izin esp
allow_anonymous true

# sertifikat ssl
cafile /mosquitto/config/certs/hvas.crt
certfile /certs/hvas.crt
keyfile /certs/hvas.key

# monitoring-service
listener 1883
allow_anonymous true